import type { Metadata } from "next";
import { ThemeProvider } from "@/app/components/theme-provider";
import { AppSidebar } from "./components/app-sidebar";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";
import {
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`antialiased`}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
          <SidebarProvider defaultOpen={false}>
            <AppSidebar />
            <main>
              {children}
            </main>
            <Toaster richColors closeButton />
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
